import { defineStore } from 'pinia'
import type { Language } from '~/types'

interface Translations {
  [key: string]: string | Translations
}

const thTranslations: Translations = {
  nav: {
    home: 'หน้าหลัก', about: 'เกี่ยวกับเรา', services: 'บริการ', campaigns: 'แคมเปญ',
    blog: 'บล็อก', contact: 'ติดต่อเรา', joinInfluencer: 'ร่วมงานกับเรา',
    login: 'เข้าสู่ระบบ', register: 'สมัครสมาชิก', logout: 'ออกจากระบบ',
    dashboard: 'แดชบอร์ด', profile: 'โปรไฟล์', wallet: 'กระเป๋าเงิน',
    myCampaigns: 'แคมเปญของฉัน', tasks: 'งาน', notifications: 'การแจ้งเตือน',
  },
  hero: {
    subtitle: 'KOL Marketplace อันดับ 1 ของไทย',
    title: 'จับคู่แบรนด์กับ Creator ตัวจริง',
    titleBefore: 'จับคู่แบรนด์กับ',
    titleHighlight: 'Creator ตัวจริง',
    description: 'หา Creator ที่ใช่ใน 48 ชั่วโมง • วัดผลเรียลไทม์',
    getStarted: 'เริ่มต้นฟรี',
    exploreCampaigns: 'ดูวิธีการทำงาน',
    stats: { influencers: 'Verified Creators', brands: 'Trusted Brands', paidOut: 'Success Rate' },
    trustBadge: 'ได้รับความไว้วางใจจากแบรนด์ชั้นนำ',
  },
  about: {
    badge: 'เกี่ยวกับเรา',
    title: 'พื้นที่ที่แบรนด์เจอ Creator ตัวจริง',
    description: 'Marketplace ยุคใหม่ — KOL ผ่านการตรวจสอบ engagement จริง วัดผลได้ทุกแคมเปญ',
    heroDescription: 'Prakast คือแพลตฟอร์มจับคู่แบรนด์กับ creator/KOL ตัวจริง ทุกคนผ่านการตรวจสอบตัวตนและ engagement แพลตฟอร์มดูแลตั้งแต่เลือก creator บรีฟงาน ตรวจเนื้อหา จนถึงออกเอกสารครบถ้วน',
    points: {
      point1: 'Creator ทุกคนผ่าน KYC และตรวจ engagement จริง ไม่มี bot',
      point2: 'ราคาโปร่งใส เอกสารครบ หัก ณ ที่จ่ายถูกต้อง ไม่มีค่าซ่อน',
      point3: 'Dashboard วัดผลเรียลไทม์ ทุกแคมเปญทุก creator',
    },
    learnMore: 'เรียนรู้เพิ่มเติม',
    stats: {
      stat1Value: '10,000+',
      stat1Label: 'Verified Creators',
      stat2Value: '500+',
      stat2Label: 'Trusted Brands',
      stat3Value: '98%',
      stat3Label: 'Success Rate',
      stat4Value: '24/7',
      stat4Label: 'Support',
    },
    story: {
      title: 'ทำไมเราสร้าง Prakast',
      paragraph1: 'วงการ KOL ในไทยโตเร็วมาก แต่แบรนด์ยังหา creator ที่ใช่ยาก ปัญหา fake followers, engagement ปลอม, สื่อสารกันวุ่นวาย — Prakast เกิดขึ้นเพื่อแก้โจทย์เหล่านี้ในที่เดียว',
      paragraph2: 'เราคัดกรอง creator ทุกคนผ่าน KYC และวิเคราะห์ engagement จริง ตัวเลขในโปรไฟล์โปร่งใส ตรวจสอบได้ ไม่มี bot ไม่มี fake',
      paragraph3: 'ตั้งแต่เลือก creator, บรีฟงาน, ตรวจเนื้อหา, go live, วัดผล จนจ่ายเงิน — จบในที่เดียว เรียลไทม์ ปลอดภัยทั้งสองฝ่าย',
    },
    values: {
      value1Title: 'ความโปร่งใส',
      value1Description: 'ทุกตัวเลขบน Prakast ตรวจสอบได้ ทั้งราคา engagement และผลงาน',
      value2Title: 'ความเชื่อถือได้',
      value2Description: 'สัญญาดิจิทัล เอกสารภาษีครบ ติดตามสถานะทุก milestone — แบรนด์และ creator ไว้ใจกันได้',
      value3Title: 'นวัตกรรม',
      value3Description: 'เครื่องมือวัดผลและ dashboard ที่ทันสมัย ช่วยคุณตัดสินใจบน data จริง',
      value4Title: 'ชุมชน',
      value4Description: 'เราเชื่อว่า creator กับแบรนด์โตไปด้วยกันได้ Prakast คือสะพานเชื่อม',
    },
    team: {
      badge: 'ทีมของเรา',
      title: 'ทีมเบื้องหลัง Prakast',
      member1Name: 'Alex K.',
      member1Role: 'Founder & CEO',
      member2Name: 'Sara T.',
      member2Role: 'Head of Product',
      member3Name: 'Chris L.',
      member3Role: 'Head of Creator Relations',
      member4Name: 'Emma P.',
      member4Role: 'Head of Brand Success',
    },
    whyUs: {
      badge: 'ทำไมต้องเลือกเรา',
      title: 'ทำไมแบรนด์เลือก Prakast',
      feature1: 'Creator ทุกคนผ่านการตรวจสอบตัวตน (KYC) และ engagement จริง',
      feature2: 'สัญญาดิจิทัล + เอกสารภาษีครบถ้วน โปร่งใสทั้งสองฝ่าย',
      feature3: 'Dashboard วัดผลเรียลไทม์ทุกแคมเปญ',
      feature4: 'Account manager ดูแลทุก campaign ตั้งแต่ต้นจนจบ',
      feature5: 'ราคาโปร่งใส ไม่มีค่าใช้จ่ายซ่อน',
      feature6: 'Support 24/7 ตอบเร็วทั้งไทยและอังกฤษ',
    },
  },
  services: {
    badge: 'บริการของเรา',
    title: 'ทุกอย่างที่คุณต้องการ จบในที่เดียว',
    description: 'ตั้งแต่หา creator ที่ใช่ ไปจนจ่ายเงินให้เสร็จ Prakast มีเครื่องมือครบพร้อมดูแลทุกขั้นตอน',
    service1: 'Creator Discovery',
    service1Desc: 'ค้นหา creator ที่ใช่ตามหมวดหมู่ งบประมาณ และกลุ่มเป้าหมาย',
    service1Feature1: 'ค้นหาด้วย filter หลายชั้น',
    service1Feature2: 'Match ตามกลุ่มเป้าหมาย',
    service1Feature3: 'แนะนำ creator อัตโนมัติ',
    service1Feature4: 'ดูผลงานย้อนหลัง',
    service2: 'Campaign Management',
    service2Desc: 'บรีฟงาน สัญญา timeline ครบจบในระบบเดียว',
    service2Feature1: 'Template บรีฟสำเร็จรูป',
    service2Feature2: 'สัญญาดิจิทัล',
    service2Feature3: 'Timeline อัตโนมัติ',
    service2Feature4: 'แจ้งเตือนทุก milestone',
    service3: 'Content Approval',
    service3Desc: 'ตรวจ draft และ approve content ก่อน go live',
    service3Feature1: 'Review draft ออนไลน์',
    service3Feature2: 'Comment/Revision flow',
    service3Feature3: 'Version tracking',
    service3Feature4: 'Approval workflow',
    service4: 'Real-time Analytics',
    service4Desc: 'วัดผล engagement reach conversion แบบเรียลไทม์',
    service4Feature1: 'Dashboard เรียลไทม์',
    service4Feature2: 'Engagement metrics',
    service4Feature3: 'ROI tracking',
    service4Feature4: 'Export รายงาน PDF',
    service5: 'Account Management',
    service5Desc: 'ทีม account manager + support 24/7 ดูแลทุก campaign',
    service5Feature1: 'Dedicated account manager',
    service5Feature2: 'Support 24/7',
    service5Feature3: 'ไทย/อังกฤษ',
    service5Feature4: 'คำปรึกษากลยุทธ์',
    service6: 'Invoice & Tax Docs',
    service6Desc: 'ใบแจ้งหนี้ดิจิทัล เอกสารภาษีครบ หัก ณ ที่จ่ายถูกต้อง',
    service6Feature1: 'ใบแจ้งหนี้ดิจิทัล',
    service6Feature2: 'เอกสารหัก ณ ที่จ่าย',
    service6Feature3: 'ติดตามสถานะจ่าย',
    service6Feature4: 'แจ้งเตือนครบกำหนด',
    howItWorks: {
      badge: 'วิธีการทำงาน',
      title: 'ง่าย โปร่งใส 4 ขั้นตอน',
      step1Title: 'เลือก Creator',
      step1Description: 'ค้นหาและเลือก creator ที่ใช่ตามกลุ่มเป้าหมาย งบประมาณ และหมวดหมู่ของแบรนด์',
      step2Title: 'บรีฟงาน',
      step2Description: 'สร้างบรีฟผ่าน template ออกสัญญาดิจิทัล วาง timeline ของแคมเปญ',
      step3Title: 'Approve & Go Live',
      step3Description: 'ตรวจ draft approve content creator โพสต์จริง ติดตามผลในทันที',
      step4Title: 'วัดผล & รับเอกสาร',
      step4Description: 'ดูผล engagement เรียลไทม์ เมื่อครบเงื่อนไข Prakast ออกใบแจ้งหนี้ + เอกสารภาษีให้อัตโนมัติ',
    },
    ctaSection: {
      title: 'พร้อมเริ่ม campaign แรกของคุณหรือยัง?',
      description: 'เริ่มทำ campaign แรกวันนี้ — หา creator ตัวจริงในไม่กี่คลิก',
      button1: 'เริ่มต้นใช้งาน',
      button2: 'ติดต่อเรา',
    },
  },
  expertise: {
    badge: 'Case Studies',
    title: 'แคมเปญที่น่าสนใจ',
    viewAll: 'ดูทั้งหมด',
  },
  testimonials: {
    badge: 'เสียงจากแบรนด์',
    title: 'แบรนด์ที่ไว้วางใจเรา',
    testimonial1: 'Prakast ทำให้เราหา creator ที่ตรงกับแบรนด์ได้ง่ายขึ้นมาก ระบบคัดกรองดี ผลงานออกมาตรงตามคาด',
    testimonial1Name: 'สมชาย ท.',
    testimonial1Role: 'Brand Director',
    testimonial2: 'ชอบที่ทุกอย่างจบในที่เดียว — บรีฟ สัญญา วัดผล จ่ายเงิน ประหยัดเวลาทีมเราไปเยอะมาก',
    testimonial2Name: 'สิริพร ป.',
    testimonial2Role: 'Marketing Manager',
    testimonial3: 'Prakast ช่วยให้เราหา creator ที่ใช่ได้ใน 48 ชั่วโมง วัดผลได้ชัดทุก campaign',
    testimonial3Name: 'อานนท์ ล.',
    testimonial3Role: 'CEO, Leading Brand',
  },
  cta: {
    title: 'พร้อมให้แบรนด์ของคุณปัง?',
    description: 'เริ่ม campaign แรกวันนี้ — หา Creator ที่ใช่ในไม่กี่คลิก ไม่มีค่าสมัคร',
    button1: 'เริ่มต้นฟรี',
    button2: 'ดูตัวอย่าง Campaign',
  },
  mediaInsights: {
    badge: 'Insights',
    title: 'เทรนด์และเคล็ดลับ KOL ล่าสุด',
    viewMore: 'อ่านเพิ่มเติม',
  },
  auth: {
    loginTitle: 'เข้าสู่ระบบ', loginSubtitle: 'ยินดีต้อนรับกลับมา! กรุณาเข้าสู่ระบบเพื่อดำเนินการต่อ',
    registerTitle: 'สมัครสมาชิก', registerSubtitle: 'สร้างบัญชีใหม่เพื่อเริ่มต้นเป็น Influencer',
    forgotPasswordTitle: 'ลืมรหัสผ่าน', forgotPasswordSubtitle: 'กรอกอีเมลของคุณเพื่อรับลิงก์รีเซ็ตรหัสผ่าน',
    resetPasswordTitle: 'รีเซ็ตรหัสผ่าน', resetPasswordSubtitle: 'กรอกรหัสผ่านใหม่ของคุณ',
    changePasswordTitle: 'เปลี่ยนรหัสผ่าน', changePasswordSubtitle: 'อัปเดตรหัสผ่านของคุณ',
    username: 'ชื่อผู้ใช้', password: 'รหัสผ่าน', email: 'อีเมล',
    confirmPassword: 'ยืนยันรหัสผ่าน', firstName: 'ชื่อ', lastName: 'นามสกุล',
    rememberMe: 'จดจำฉัน', forgotPassword: 'ลืมรหัสผ่าน?',
    noAccount: 'ยังไม่มีบัญชี?', haveAccount: 'มีบัญชีแล้ว?',
    registerNow: 'สมัครสมาชิก', loginNow: 'เข้าสู่ระบบ',
    sendResetLink: 'ส่งลิงก์รีเซ็ต', resetPassword: 'รีเซ็ตรหัสผ่าน',
    changePassword: 'เปลี่ยนรหัสผ่าน', oldPassword: 'รหัสผ่านเดิม', newPassword: 'รหัสผ่านใหม่',
    orContinueWith: 'หรือดำเนินการต่อด้วย', loginSuccess: 'เข้าสู่ระบบสำเร็จ',
    registerSuccess: 'สมัครสมาชิกสำเร็จ', passwordResetSent: 'ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว',
    passwordChanged: 'เปลี่ยนรหัสผ่านสำเร็จ',
  },
  dashboard: {
    title: 'แดชบอร์ด', welcome: 'ยินดีต้อนรับกลับ', summary: 'สรุป',
    walletBalance: 'ยอดเงินในกระเป๋า', activeCampaigns: 'แคมเปญที่กำลังทำ',
    pendingTasks: 'งานที่ต้องส่ง', revisionTasks: 'งานที่ต้องแก้ไข',
    recentTransactions: 'ประวัติการรับเงินล่าสุด', notifications: 'การแจ้งเตือน',
    viewAll: 'ดูทั้งหมด', noNotifications: 'ไม่มีการแจ้งเตือน', markAsRead: 'อ่านแล้ว',
    newCampaign: 'แคมเปญใหม่', taskApproved: 'งานได้รับการอนุมัติ', paymentReceived: 'ได้รับการโอนเงิน',
  },
  profile: {
    title: 'โปรไฟล์', personalInfo: 'ข้อมูลส่วนตัว', socialAccounts: 'บัญชีโซเชียล',
    categories: 'หมวดหมู่ / Niche', rateCard: 'Rate Card',
    verification: 'ยืนยันตัวตน / KYC', verificationStatus: 'สถานะการยืนยัน',
    pending: 'รอตรวจสอบ', approved: 'อนุมัติแล้ว', rejected: 'ถูกปฏิเสธ',
    uploadDocument: 'อัปโหลดเอกสาร', idCard: 'บัตรประชาชน', selfie: 'เซลฟี่คู่บัตรประชาชน', bankBook: 'หน้าสมุดบัญชีธนาคาร',
    saveChanges: 'บันทึกการเปลี่ยนแปลง', editProfile: 'แก้ไขโปรไฟล์', bio: 'เกี่ยวกับฉัน',
    phone: 'เบอร์โทรศัพท์', location: 'ที่อยู่',
  },
  campaigns: {
    title: 'แคมเปญ', marketplace: 'ตลาดแคมเปญ', featured: 'แคมเปญแนะนำ',
    allCampaigns: 'แคมเปญทั้งหมด', filter: 'กรอง', category: 'หมวดหมู่', budget: 'งบประมาณ',
    followers: 'ผู้ติดตาม', platform: 'แพลตฟอร์ม', apply: 'สมัคร', applied: 'สมัครแล้ว',
    details: 'รายละเอียด', requirements: 'ข้อกำหนด', deadline: 'วันสิ้นสุด',
    influencersNeeded: 'ต้องการ Influencer', joined: 'เข้าร่วมแล้ว', budgetRange: 'ช่วงราคา',
  },
  tasks: {
    title: 'งาน', subtitle: 'จัดการงานแคมเปญของคุณ',
    myTasks: 'งานของฉัน', pending: 'รอดำเนินการ', inProgress: 'กำลังทำ',
    submitted: 'ส่งแล้ว', revision: 'ต้องแก้ไข', approved: 'อนุมัติแล้ว',
    waitingGoLive: 'รอ Go Live', done: 'Go Live ✓',
    noTasks: 'ไม่มีงานในหมวดหมู่นี้',
    campaign: 'แคมเปญ', dueDate: 'กำหนดส่ง', payment: 'ค่าตอบแทน',
    description: 'รายละเอียด',
    comments: 'ความคิดเห็น', noComments: 'ยังไม่มีความคิดเห็น',
    addComment: 'เพิ่มความคิดเห็น', commentPlaceholder: 'พิมพ์ความคิดเห็น...',
    postComment: 'โพสต์ความคิดเห็น',
    submitWork: 'ส่งงาน', resubmitWork: 'ส่งงานใหม่',
    draftContent: 'Draft Content / Caption',
    draftContentPlaceholder: 'เขียน caption หรือรายละเอียด content ที่จะโพสต์...',
    attachFile: 'แนบไฟล์ (รูป / วิดีโอ)', chooseFile: 'คลิกเพื่อเลือกไฟล์',
    revisionNote: 'ต้องแก้ไข', revisionDesc: 'กรุณาตรวจสอบ comment และ resubmit งาน',
    draftContentRevised: 'Draft Content / Caption (แก้ไขแล้ว)',
    draftContentRevisedPlaceholder: 'เขียน caption หรือรายละเอียด content ที่แก้ไขแล้ว...',
    attachFileRevised: 'แนบไฟล์ที่แก้ไขแล้ว (รูป / วิดีโอ)',
    readyGoLive: 'พร้อม Go Live แล้ว!',
    goLiveDesc: 'Draft ได้รับการอนุมัติ กรุณาโพสต์งานจริงและแนบลิ้งด้านล่าง',
    postUrl: 'ลิ้งโพสต์จริง (Post URL)', confirmGoLive: 'ยืนยัน Go Live',
    goneLive: 'Go Live เรียบร้อยแล้ว', postLink: 'ลิ้งโพสต์:',
    viewDetails: 'ดูรายละเอียด', attachments: 'ไฟล์แนบ', uploadFile: 'อัปโหลดไฟล์',
    due: 'กำหนดส่ง',
  },
  wallet: {
    title: 'กระเป๋าเงิน', balance: 'ยอดเงิน', transactionHistory: 'ประวัติธุรกรรม',
    income: 'รายรับ', withdrawal: 'ถอนเงิน', pending: 'รอดำเนินการ', completed: 'สำเร็จ',
    failed: 'ล้มเหลว', withdraw: 'ถอนเงิน', bankAccount: 'บัญชีธนาคาร', amount: 'จำนวนเงิน',
    requestWithdrawal: 'ขอถอนเงิน', noTransactions: 'ไม่มีธุรกรรม',
  },
  common: {
    loading: 'กำลังโหลด...', save: 'บันทึก', cancel: 'ยกเลิก', edit: 'แก้ไข', delete: 'ลบ',
    confirm: 'ยืนยัน', close: 'ปิด', search: 'ค้นหา', filter: 'กรอง', sort: 'เรียงลำดับ',
    next: 'ถัดไป', previous: 'ก่อนหน้า', submit: 'ส่ง', back: 'กลับ', more: 'เพิ่มเติม',
    readMore: 'อ่านเพิ่มเติม', viewAll: 'ดูทั้งหมด', seeDetails: 'ดูรายละเอียด',
    learnMore: 'เรียนรู้เพิ่มเติม', getStarted: 'เริ่มต้นใช้งาน', contactUs: 'ติดต่อเรา',
    followUs: 'ติดตามเรา', subscribe: 'สมัครรับข่าวสาร', emailPlaceholder: 'กรอกอีเมลของคุณ',
    allRightsReserved: 'สงวนลิขสิทธิ์', privacyPolicy: 'นโยบายความเป็นส่วนตัว',
    termsOfService: 'เงื่อนไขการใช้บริการ', cookiePolicy: 'นโยบายคุกกี้',
    companyName: 'Prakast',
    subject: 'หัวข้อ',
    message: 'ข้อความ',
  },
  footer: {
    description: 'Marketplace KOL & Influencer ยุคใหม่ — สำหรับแบรนด์และ creator ในประเทศไทย',
    quickLinks: 'ลิงก์ด่วน', services: 'บริการ', newsletter: 'รับข่าวสาร',
    newsletterDesc: 'รับเทรนด์และเคล็ดลับ KOL ล่าสุด', forInfluencers: 'สำหรับ Creator',
    forBrands: 'สำหรับแบรนด์', pricing: 'ราคา', support: 'ช่วยเหลือ',
  },
  contact: {
    badge: 'ติดต่อเรา',
    title: 'ติดต่อเรา',
    subtitle: 'มีคำถาม? เรายินดีรับฟัง ส่งข้อความหาเราและเราจะตอบกลับโดยเร็วที่สุด',
    info: {
      emailTitle: 'อีเมล',
      emailDesc: 'สำหรับข้อสงสัยทั่วไป',
      phoneTitle: 'โทรศัพท์',
      phoneDesc: 'จันทร์–ศุกร์ 9.00–18.00 น.',
      officeTitle: 'สำนักงาน',
      officeContent: 'กรุงเทพฯ, ประเทศไทย',
      officeDesc: '88 ซอยสุขุมวิท 62 แขวงพระโขนงใต้ เขตพระโขนง',
      hoursTitle: 'เวลาทำการ',
      hoursContent: 'จันทร์ – ศุกร์: 9.00 – 18.00 น.',
      hoursDesc: 'เสาร์–อาทิตย์: ปิดทำการ',
    },
    form: {
      title: 'ส่งข้อความถึงเรา',
      namePlaceholder: 'ชื่อของคุณ',
      emailPlaceholder: 'your@email.com',
      subjectPlaceholder: 'เราจะช่วยคุณได้อย่างไร?',
      messagePlaceholder: 'บอกรายละเอียดเพิ่มเติมเกี่ยวกับสิ่งที่ต้องการ...',
      sending: 'กำลังส่ง...',
      send: 'ส่งข้อความ',
      successTitle: 'ส่งข้อความแล้ว!',
      successDesc: 'เราจะติดต่อกลับหาคุณโดยเร็วที่สุด',
    },
    office: {
      title: 'เยี่ยมชมสำนักงานเรา',
      address: '88 ซอยสุขุมวิท 62 กรุงเทพฯ, ประเทศไทย',
    },
    faq: {
      title: 'คำถามที่พบบ่อย',
      description: 'ค้นหาคำตอบสำหรับคำถามทั่วไปได้ในส่วน FAQ ของเรา',
      button: 'ดู FAQ',
    },
  },
  error: {
    404: { title: 'ไม่พบหน้านี้', description: 'ขออภัย หน้าที่คุณกำลังค้นหาไม่มีอยู่', backHome: 'กลับหน้าหลัก' },
    500: { title: 'ข้อผิดพลาดของเซิร์ฟเวอร์', description: 'ขออภัย เกิดข้อผิดพลาดบางอย่าง กรุณาลองใหม่อีกครั้ง', tryAgain: 'ลองใหม่' },
  },
}

const enTranslations: Translations = {
  nav: {
    home: 'Home', about: 'About', services: 'Services', campaigns: 'Campaigns',
    blog: 'Blog', contact: 'Contact', joinInfluencer: 'Join Us',
    login: 'Login', register: 'Register', logout: 'Logout',
    dashboard: 'Dashboard', profile: 'Profile', wallet: 'Wallet',
    myCampaigns: 'My Campaigns', tasks: 'Tasks',
  },
  hero: {
    subtitle: "Thailand's #1 KOL Marketplace",
    title: 'Where Brands Meet Real Creators',
    titleBefore: 'Where Brands Meet',
    titleHighlight: 'Real Creators',
    description: 'Find the right creator in 48 hours • Real-time analytics • Transparent invoicing — all in one platform',
    getStarted: 'Start Free', exploreCampaigns: 'See How It Works',
    stats: { influencers: 'Verified Creators', brands: 'Trusted Brands', paidOut: 'Success Rate' },
    trustBadge: 'Trusted by leading brands',
  },
  about: {
    badge: 'About Us',
    title: 'Where Brands Meet Real Creators',
    description: 'A modern marketplace — verified creators, real engagement, measurable results on every campaign',
    heroDescription: 'Prakast is a marketplace that connects brands with real, verified creators. Every KOL passes identity and engagement verification. From discovery to briefing, content approval, through to compliant invoicing — everything lives in one place.',
    points: {
      point1: 'Every creator is KYC-verified with real engagement — no bots',
      point2: 'Transparent pricing, full documentation, correct withholding tax — no hidden fees',
      point3: 'Real-time analytics on every campaign, every creator',
    },
    learnMore: 'Learn More',
    stats: {
      stat1Value: '10,000+',
      stat1Label: 'Verified Creators',
      stat2Value: '500+',
      stat2Label: 'Trusted Brands',
      stat3Value: '98%',
      stat3Label: 'Success Rate',
      stat4Value: '24/7',
      stat4Label: 'Support',
    },
    story: {
      title: 'Why We Built Prakast',
      paragraph1: "Thailand's KOL scene is booming, but brands still struggle to find the right creators. Fake followers, inflated engagement, messy communication — we built Prakast to solve these problems in one place.",
      paragraph2: 'We screen every creator through KYC and real engagement analysis. Profile numbers are transparent and verifiable. No bots, no fake metrics.',
      paragraph3: 'From discovery, briefing, content review, go-live, measurement to payment — all in one platform. Real-time, secure, protected for both sides.',
    },
    values: {
      value1Title: 'Transparency',
      value1Description: 'Every number on Prakast is verifiable — pricing, engagement, and results.',
      value2Title: 'Trust',
      value2Description: 'Digital contracts, complete tax docs, tracked milestones — trust between brands and creators.',
      value3Title: 'Innovation',
      value3Description: 'Modern analytics and dashboards help you decide with real data.',
      value4Title: 'Community',
      value4Description: 'Creators and brands grow together. Prakast is the bridge.',
    },
    team: {
      badge: 'Our Team',
      title: 'The Team Behind Prakast',
      member1Name: 'Alex K.',
      member1Role: 'Founder & CEO',
      member2Name: 'Sara T.',
      member2Role: 'Head of Product',
      member3Name: 'Chris L.',
      member3Role: 'Head of Creator Relations',
      member4Name: 'Emma P.',
      member4Role: 'Head of Brand Success',
    },
    whyUs: {
      badge: 'Why Choose Us',
      title: 'Why Brands Choose Prakast',
      feature1: 'Every creator is KYC-verified with real engagement',
      feature2: 'Digital contracts + full tax documentation — transparent on both sides',
      feature3: 'Real-time analytics on every campaign',
      feature4: 'Dedicated account manager for every campaign',
      feature5: 'Transparent pricing, no hidden fees',
      feature6: '24/7 support in Thai and English',
    },
  },
  services: {
    badge: 'Our Services',
    title: 'Everything You Need, All in One Place',
    description: 'From finding the right creator to processing payment, Prakast has every tool you need to run a successful campaign.',
    service1: 'Creator Discovery',
    service1Desc: 'Find the right creator by category, budget, and target audience',
    service1Feature1: 'Multi-layer filters',
    service1Feature2: 'Audience matching',
    service1Feature3: 'AI recommendations',
    service1Feature4: 'Past work portfolio',
    service2: 'Campaign Management',
    service2Desc: 'Briefs, contracts, and timelines — all in one system',
    service2Feature1: 'Brief templates',
    service2Feature2: 'Digital contracts',
    service2Feature3: 'Automated timelines',
    service2Feature4: 'Milestone alerts',
    service3: 'Content Approval',
    service3Desc: 'Review drafts and approve content before go-live',
    service3Feature1: 'Online draft review',
    service3Feature2: 'Comment & revision flow',
    service3Feature3: 'Version tracking',
    service3Feature4: 'Approval workflow',
    service4: 'Real-time Analytics',
    service4Desc: 'Measure engagement, reach, and conversion in real time',
    service4Feature1: 'Real-time dashboards',
    service4Feature2: 'Engagement metrics',
    service4Feature3: 'ROI tracking',
    service4Feature4: 'PDF export',
    service5: 'Account Management',
    service5Desc: 'Dedicated account managers and 24/7 support for every campaign',
    service5Feature1: 'Dedicated account manager',
    service5Feature2: '24/7 support',
    service5Feature3: 'Thai/English',
    service5Feature4: 'Strategic guidance',
    service6: 'Invoice & Tax Docs',
    service6Desc: 'Digital invoices, complete tax documentation, correct withholding',
    service6Feature1: 'Digital invoices',
    service6Feature2: 'Withholding tax docs',
    service6Feature3: 'Payment status tracking',
    service6Feature4: 'Due-date reminders',
    howItWorks: {
      badge: 'How It Works',
      title: 'Simple, Transparent, 4 Steps',
      step1Title: 'Pick a Creator',
      step1Description: 'Search and select the right creator by target audience, budget, and brand category.',
      step2Title: 'Brief the Work',
      step2Description: 'Create briefs from templates, issue digital contracts, set campaign timelines.',
      step3Title: 'Approve & Go Live',
      step3Description: 'Review drafts, approve content, creator posts the live work, track results instantly.',
      step4Title: 'Measure & Document',
      step4Description: 'Track engagement in real time. When conditions are met, Prakast auto-generates invoices and tax docs.',
    },
    ctaSection: {
      title: 'Ready to Launch Your First Campaign?',
      description: 'Launch your first creator campaign today — find real creators in just a few clicks.',
      button1: 'Get Started',
      button2: 'Contact Us',
    },
  },
  expertise: {
    badge: 'Case Studies',
    title: 'Featured Campaigns',
    viewAll: 'View All',
  },
  testimonials: {
    badge: 'Brand Voices',
    title: 'Brands That Trust Us',
    testimonial1: 'Prakast made finding brand-aligned creators so much easier. The screening is solid and results hit expectations every time.',
    testimonial1Name: 'Somchai T.',
    testimonial1Role: 'Brand Director',
    testimonial2: 'I love that everything happens in one place — briefs, contracts, analytics, payment. It saves our team a huge amount of time.',
    testimonial2Name: 'Siriporn P.',
    testimonial2Role: 'Marketing Manager',
    testimonial3: 'Prakast helped us find the right creator within 48 hours. Every campaign comes with clear, measurable results.',
    testimonial3Name: 'Ananda L.',
    testimonial3Role: 'CEO, Leading Brand',
  },
  cta: {
    title: 'Ready to Make Your Brand Pop?',
    description: 'Launch your first campaign today — find the right creator in a few clicks. No sign-up fee.',
    button1: 'Start Free',
    button2: 'See Example Campaigns',
  },
  mediaInsights: {
    badge: 'Insights',
    title: 'Latest KOL Trends & Tips',
    viewMore: 'Read More',
  },
  auth: {
    loginTitle: 'Login', loginSubtitle: 'Welcome back! Please login to continue',
    registerTitle: 'Register', registerSubtitle: 'Create a new account to start as an Influencer',
    forgotPasswordTitle: 'Forgot Password', forgotPasswordSubtitle: 'Enter your email to receive a password reset link',
    resetPasswordTitle: 'Reset Password', resetPasswordSubtitle: 'Enter your new password',
    changePasswordTitle: 'Change Password', changePasswordSubtitle: 'Update your password',
    username: 'Username', password: 'Password', email: 'Email',
    confirmPassword: 'Confirm Password', firstName: 'First Name', lastName: 'Last Name',
    rememberMe: 'Remember me', forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?", haveAccount: 'Already have an account?',
    registerNow: 'Register now', loginNow: 'Login now',
    sendResetLink: 'Send Reset Link', resetPassword: 'Reset Password',
    changePassword: 'Change Password', oldPassword: 'Old Password', newPassword: 'New Password',
    orContinueWith: 'Or continue with', loginSuccess: 'Login successful',
    registerSuccess: 'Registration successful', passwordResetSent: 'Password reset link sent',
    passwordChanged: 'Password changed successfully',
  },
  dashboard: {
    title: 'Dashboard', welcome: 'Welcome back', summary: 'Summary',
    walletBalance: 'Wallet Balance', activeCampaigns: 'Active Campaigns',
    pendingTasks: 'Pending Tasks', revisionTasks: 'Tasks Need Revision',
    recentTransactions: 'Recent Transactions', notifications: 'Notifications',
    viewAll: 'View All', noNotifications: 'No notifications', markAsRead: 'Mark as read',
    newCampaign: 'New Campaign', taskApproved: 'Task Approved', paymentReceived: 'Payment Received',
  },
  profile: {
    title: 'Profile', personalInfo: 'Personal Information', socialAccounts: 'Social Accounts',
    categories: 'Categories / Niche', rateCard: 'Rate Card',
    verification: 'Verification / KYC', verificationStatus: 'Verification Status',
    pending: 'Pending', approved: 'Approved', rejected: 'Rejected',
    uploadDocument: 'Upload Document', idCard: 'ID Card', selfie: 'Selfie with ID', bankBook: 'Bank Book',
    saveChanges: 'Save Changes', editProfile: 'Edit Profile', bio: 'About Me',
    phone: 'Phone', location: 'Location',
  },
  campaigns: {
    title: 'Campaigns', marketplace: 'Campaign Marketplace', featured: 'Featured Campaigns',
    allCampaigns: 'All Campaigns', filter: 'Filter', category: 'Category', budget: 'Budget',
    followers: 'Followers', platform: 'Platform', apply: 'Apply', applied: 'Applied',
    details: 'Details', requirements: 'Requirements', deadline: 'Deadline',
    influencersNeeded: 'Influencers Needed', joined: 'Joined', budgetRange: 'Budget Range',
  },
  tasks: {
    title: 'Tasks', subtitle: 'Manage your campaign tasks',
    myTasks: 'My Tasks', pending: 'Pending', inProgress: 'In Progress',
    submitted: 'Submitted', revision: 'Needs Revision', approved: 'Approved',
    waitingGoLive: 'Awaiting Go Live', done: 'Go Live ✓',
    noTasks: 'No tasks in this category.',
    campaign: 'Campaign', dueDate: 'Due Date', payment: 'Payment',
    description: 'Description',
    comments: 'Comments', noComments: 'No comments yet.',
    addComment: 'Add Comment', commentPlaceholder: 'Type your comment...',
    postComment: 'Post Comment',
    submitWork: 'Submit Work', resubmitWork: 'Resubmit Work',
    draftContent: 'Draft Content / Caption',
    draftContentPlaceholder: 'Write your caption or content description...',
    attachFile: 'Attach File (Image / Video)', chooseFile: 'Click to choose file',
    revisionNote: 'Needs Revision', revisionDesc: 'Please review the comments and resubmit your work',
    draftContentRevised: 'Draft Content / Caption (Revised)',
    draftContentRevisedPlaceholder: 'Write your revised caption or content...',
    attachFileRevised: 'Attach Revised File (Image / Video)',
    readyGoLive: 'Ready to Go Live!',
    goLiveDesc: 'Draft approved. Please post your content and submit the link below.',
    postUrl: 'Post URL', confirmGoLive: 'Confirm Go Live',
    goneLive: 'Successfully Gone Live', postLink: 'Post Link:',
    viewDetails: 'View Details', attachments: 'Attachments', uploadFile: 'Upload File',
    due: 'Due',
  },
  wallet: {
    title: 'Wallet', balance: 'Balance', transactionHistory: 'Transaction History',
    income: 'Income', withdrawal: 'Withdrawal', pending: 'Pending', completed: 'Completed',
    failed: 'Failed', withdraw: 'Withdraw', bankAccount: 'Bank Account', amount: 'Amount',
    requestWithdrawal: 'Request Withdrawal', noTransactions: 'No transactions',
  },
  common: {
    loading: 'Loading...', save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete',
    confirm: 'Confirm', close: 'Close', search: 'Search', filter: 'Filter', sort: 'Sort',
    next: 'Next', previous: 'Previous', submit: 'Submit', back: 'Back', more: 'More',
    readMore: 'Read More', viewAll: 'View All', seeDetails: 'See Details',
    learnMore: 'Learn More', getStarted: 'Get Started', contactUs: 'Contact Us',
    followUs: 'Follow Us', subscribe: 'Subscribe', emailPlaceholder: 'Enter your email',
    allRightsReserved: 'All rights reserved', privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service', cookiePolicy: 'Cookie Policy',
    companyName: 'Prakast',
    subject: 'Subject',
    message: 'Message',
  },
  footer: {
    description: 'Modern KOL & influencer marketplace — for brands and creators in Thailand',
    quickLinks: 'Quick Links', services: 'Services', newsletter: 'Newsletter',
    newsletterDesc: 'Get the latest KOL trends and tips', forInfluencers: 'For Creators',
    forBrands: 'For Brands', pricing: 'Pricing', support: 'Support',
  },
  contact: {
    badge: 'Contact Us',
    title: 'Get in Touch',
    subtitle: "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    info: {
      emailTitle: 'Email',
      emailDesc: 'For general inquiries',
      phoneTitle: 'Phone',
      phoneDesc: 'Mon–Fri 9am–6pm',
      officeTitle: 'Office',
      officeContent: 'Bangkok, Thailand',
      officeDesc: '88 Soi Sukhumvit 62 Section 3, Phra Khanong Tai, Phra Khanong',
      hoursTitle: 'Working Hours',
      hoursContent: 'Mon – Fri: 9AM – 6PM',
      hoursDesc: 'Weekend: Closed',
    },
    form: {
      title: 'Send us a Message',
      namePlaceholder: 'Your name',
      emailPlaceholder: 'your@email.com',
      subjectPlaceholder: 'How can we help?',
      messagePlaceholder: 'Tell us more about your inquiry...',
      sending: 'Sending...',
      send: 'Send Message',
      successTitle: 'Message sent!',
      successDesc: "We'll get back to you as soon as possible.",
    },
    office: {
      title: 'Visit Our Office',
      address: '88 Soi Sukhumvit 62, Bangkok, Thailand',
    },
    faq: {
      title: 'Frequently Asked Questions',
      description: 'Find quick answers to common questions in our FAQ section.',
      button: 'View FAQ',
    },
  },
  error: {
    404: { title: 'Page Not Found', description: 'Sorry, the page you are looking for does not exist', backHome: 'Back to Home' },
    500: { title: 'Server Error', description: 'Sorry, something went wrong. Please try again later', tryAgain: 'Try Again' },
  },
}

export const useLanguageStore = defineStore('language', () => {
  const language = ref<Language>('th')

  function init() {
    if (import.meta.client) {
      const stored = localStorage.getItem('kol_language') as Language
      if (stored && (stored === 'th' || stored === 'en')) {
        language.value = stored
      }
    }
  }

  function setLanguage(lang: Language) {
    language.value = lang
    if (import.meta.client) {
      localStorage.setItem('kol_language', lang)
    }
  }

  function t(key: string): string {
    const translations = language.value === 'th' ? thTranslations : enTranslations
    const keys = key.split('.')
    let value: string | Translations = translations
    for (const k of keys) {
      if (typeof value === 'object' && value !== null && k in value) {
        value = value[k] as string | Translations
      } else {
        return key
      }
    }
    return typeof value === 'string' ? value : key
  }

  return { language, init, setLanguage, t }
})
