import { defineStore } from 'pinia'
import type { Language } from '~/types'

interface Translations {
  [key: string]: string | Translations
}

const thTranslations: Translations = {
  nav: {
    home: 'หน้าหลัก', about: 'เกี่ยวกับเรา', services: 'บริการ', campaigns: 'แคมเปญ',
    blog: 'บล็อก', contact: 'ติดต่อเรา', joinInfluencer: 'ร่วมมือกับเรา',
    login: 'เข้าสู่ระบบ', register: 'สมัครสมาชิก', logout: 'ออกจากระบบ',
    dashboard: 'แดชบอร์ด', profile: 'โปรไฟล์', wallet: 'กระเป๋าเงิน',
    myCampaigns: 'แคมเปญของฉัน', tasks: 'งาน', notifications: 'การแจ้งเตือน',
  },
  hero: {
    subtitle: 'Media Planning Excellence',
    title: 'Media Planning Excellence',
    description: '41 ปีของความเชี่ยวชาญในสื่อและการวางแผน ประเทศไทยอยู่บนเครือข่ายสื่อที่เชื่อถือได้',
    getStarted: 'ขอคำปรึกษา',
    exploreCampaigns: 'บริการของเรา',
    stats: { influencers: 'ผู้เชี่ยวชาญ', brands: 'ตั้งแต่ปี', paidOut: 'ปีที่มี' },
  },
  about: {
    badge: 'เกี่ยวกับเรา',
    title: 'สำนักงานสื่อชั้นนำของประเทศไทย',
    description: 'ประสบการณ์ 41 ปีด้านการวางแผนสื่อ ซื้อสื่อ และกลยุทธ์สื่อ',
    heroDescription: 'Prakit Media คือสำนักงานสื่อชั้นนำของประเทศไทยที่มีความเชี่ยวชาญสูงในการจัดเต็มโซลูชั่นสื่อ ด้วยประสบการณ์ 41 ปี เราร่วมมือกับแบรนด์ชั้นนำเพื่อสร้างกลยุทธ์สื่อที่มีความหมายสำคัญ',
    points: {
      point1: '40+ ผู้เชี่ยวชาญด้านการวางแผนและกลยุทธ์สื่อ',
      point2: 'เครื่องมือสื่อครบครัน และเข้าถึง Nielsen data',
      point3: 'ราคาสื่อดีเยี่ยมผ่านเครือข่ายตลาดที่แข็งแกร่ง',
    },
    learnMore: 'เรียนรู้เพิ่มเติม',
    stats: {
      stat1Value: '40+',
      stat1Label: 'ผู้เชี่ยวชาญด้านกลยุทธ์',
      stat2Value: '1978',
      stat2Label: 'ปีที่ก่อตั้ง',
      stat3Value: '41',
      stat3Label: 'ปีแห่งความเป็นเลิศ',
      stat4Value: '98%',
      stat4Label: 'ความพึงพอใจของลูกค้า',
    },
    story: {
      title: 'เรื่องราวของเรา',
      paragraph1: 'ตั้งตั้งแต่ปี 1978 Prakit Media เริ่มต้นด้วยวิสัยทัศน์ที่เรียบง่าย: เป็นพันธมิตรด้านการวางแผนสื่อที่เชื่อถือได้ของประเทศไทย ในช่วง 41 ปีที่ผ่านมา เราสร้างความสัมพันธ์อันลึกซึ้งกับเครือข่ายสื่อและพัฒนาข้อมูลเชิงลึกที่เป็นกรรมสิทธิ์ที่ให้ผลลัพธ์',
      paragraph2: 'วันนี้ เราใช้เทคโนโลยีชั้นสูงและการวิเคราะห์ข้อมูลเพื่อสร้างกลยุทธ์สื่อที่ให้ผลกระทบที่วัดได้ ทีมของเรากับกว่า 40+ ผู้เชี่ยวชาญด้านการวางแผนสื่อเข้าใจความซับซ้อนของทุกช่องทางสื่อและส่วนของผู้ชม',
      paragraph3: 'เราภูมิใจที่ได้ร่วมมือกับแบรนด์ชั้นนำของประเทศไทย ช่วยให้พวกเขาเพิ่มผลประกอบการสื่อและเข้าถึงผู้ชมเป้าหมายด้วยความแม่นยำและความสร้างสรรค์',
    },
    values: {
      value1Title: 'ความเชื่อถือ',
      value1Description: 'เราสร้างความสัมพันธ์ในระยะยาวบนพื้นฐานของความโปร่งใสและการส่งมอบตามคำสัญญา',
      value2Title: 'ความเป็นเลิศ',
      value2Description: 'เราบริหารงานด้วยความเป็นเลิศในทุกด้าน ตั้งแต่การพัฒนากลยุทธ์ไปจนถึงการดำเนินการแคมเปญ',
      value3Title: 'นวัตกรรม',
      value3Description: 'เรารับเอาเทคโนโลยีใหม่และระเบียบวิธีใหม่เพื่อนำหน้าแนวโน้มตลาด',
      value4Title: 'ความร่วมมือ',
      value4Description: 'เราเห็นตัวเองว่าเป็นพันธมิตรที่แท้จริงในความสำเร็จของลูกค้า ลงทุนในการเติบโตของพวกเขา',
    },
    team: {
      badge: 'ทีมของเรา',
      title: 'พบกับผู้เชี่ยวชาญ',
      member1Name: 'นายประกิต อภิสารธนรักษ์',
      member1Role: 'ประธานและ ประธานกรรมการ',
      member2Name: 'นายพิศาล ประหัษฎางกูร',
      member2Role: 'รองประธานกรรมการบริหาร',
      member3Name: 'นายปรีชา เชาวโชติช่วง',
      member3Role: 'กรรมการผู้จัดการ',
      member4Name: 'นายวิเชียร นาคอินทนนท์',
      member4Role: 'กรรมการผู้จัดการ',
    },
    whyUs: {
      badge: 'ทำไมต้องเลือกเรา',
      title: 'ความแตกต่างของ Prakit',
      feature1: 'ประสบการณ์ 41 ปีด้านสื่อที่ได้รับการพิสูจน์',
      feature2: 'ความสัมพันธ์โดยตรงกับเครือข่ายสื่อหลักทั้งหมด',
      feature3: 'การวิเคราะห์ข้อมูลขั้นสูงและข้อมูลเชิงลึก Nielsen',
      feature4: 'การจัดการบัญชีเฉพาะเจาะจง',
      feature5: 'ราคาที่โปร่งใสและมีความสามารถในการแข่งขัน',
      feature6: 'การรายงานอย่างละเอียดและการปรับปรุง',
    },
  },
  services: {
    badge: 'บริการของเรา',
    title: 'ทุกสิ่งที่คุณต้องสำเร็จ',
    description: 'จากการวางแผนประจำปีไปจนถึงข้อมูลข่าวสารตลาด Prakit มอบโซลูชั่นสื่อที่ครอบคลุมซึ่งปรับให้เหมาะกับความต้องการของแบรนด์ของคุณ',
    service1: 'วางแผนสื่อประจำปี',
    service1Desc: 'กลยุทธ์สื่อประจำปีที่ครอบคลุมพร้อมการวิเคราะห์เชิงลึก',
    service1Feature1: 'กลยุทธ์ที่ครอบคลุม',
    service1Feature2: 'กำหนดเป้าหมายผู้ชม',
    service1Feature3: 'การปรับปรุงงบประมาณ',
    service1Feature4: 'การวางแผนสายการส่ง',
    service2: 'การซื้อสื่อ',
    service2Desc: 'การวางตำแหน่งสื่อที่ปลอดภัยพร้อมอัตราตลาดที่ดีที่สุด',
    service2Feature1: 'อัตราตลาดที่ดีที่สุด',
    service2Feature2: 'วางตำแหน่งที่ปลอดภัย',
    service2Feature3: 'ความสัมพันธ์เครือข่าย',
    service2Feature4: 'การจัดเวลาที่ยืดหยุ่น',
    service3: 'การวิเคราะห์รายเดือน',
    service3Desc: 'วิเคราะห์ค่าใช้จ่ายและการแข่งขันตลาดโดยละเอียด',
    service3Feature1: 'การวิเคราะห์การใช้จ่าย',
    service3Feature2: 'ข้อมูลเชิงลึกด้านการแข่งขัน',
    service3Feature3: 'แนวโน้มตลาด',
    service3Feature4: 'เมตริกส์ประสิทธิภาพ',
    service4: 'รายงานประสิทธิภาพ',
    service4Desc: 'การติดตามและข้อมูลเชิงลึก Echo media performance',
    service4Feature1: 'การติดตามแบบเรียลไทม์',
    service4Feature2: 'แดชบอร์ดประสิทธิภาพ',
    service4Feature3: 'การวิเคราะห์ ROI',
    service4Feature4: 'คำแนะนำในการปรับปรุง',
    service5: 'ปรึกษากลยุทธ์',
    service5Desc: 'ผู้เชี่ยวชาญ 40+ คนให้คำแนะนำแบบมืออาชีพ',
    service5Feature1: 'คำแนะนำจากผู้เชี่ยวชาญ',
    service5Feature2: 'การวางแผนกลยุทธ์',
    service5Feature3: 'ความเชี่ยวชาญด้านตลาด',
    service5Feature4: 'การจัดการบัญชี',
    service6: 'ข้อมูลข่าวสารตลาด',
    service6Desc: 'เข้าถึง Nielsen data และแนวโน้มสื่อ',
    service6Feature1: 'การเข้าถึง Nielsen data',
    service6Feature2: 'ข้อมูลข่าวสารตลาด',
    service6Feature3: 'การพยากรณ์แนวโน้ม',
    service6Feature4: 'การวิเคราะห์การแข่งขัน',
    howItWorks: {
      badge: 'วิธีการทำงาน',
      title: 'กระบวนการที่เรียบง่ายและโปร่งใส',
      step1Title: 'การพัฒนากลยุทธ์',
      step1Description: 'เราวิเคราะห์เป้าหมายแบรนด์และผู้ชมเป้าหมายของคุณเพื่อพัฒนากลยุทธ์สื่อแบบกำหนดเองของคุณ',
      step2Title: 'การวางแผนสื่อ',
      step2Description: 'ผู้เชี่ยวชาญของเราวางแผนการผสมผสานช่องทางและไทม์ไลน์ที่เหมาะสมเพื่อเพิ่มผลประกอบการสื่อของคุณ',
      step3Title: 'การดำเนินการแคมเปญ',
      step3Description: 'เราจัดหาตำแหน่งและดำเนินการแคมเปญของคุณด้วยความแม่นยำและการให้ความสำคัญต่ออยู่รายละเอียด',
      step4Title: 'การติดตามประสิทธิภาพ',
      step4Description: 'ติดตามประสิทธิภาพแบบเรียลไทม์และรับข้อมูลเชิงลึกสม่ำเสมอเพื่อปรับปรุงแคมเปญของคุณ',
    },
    ctaSection: {
      title: 'พร้อมที่จะแปลงกลยุทธ์สื่อของคุณหรือ',
      description: 'ร่วมมือกับสำนักงานสื่อชั้นนำของประเทศไทยและปลดล็อคศักยภาพเต็มที่ของแบรนด์ของคุณ',
      button1: 'ขอคำปรึกษา',
      button2: 'เรื่องราวของเรา',
    },
  },
  expertise: {
    badge: 'ความเชี่ยวชาญของเรา',
    title: 'โซลูชั่นสื่อ และกรณีศึกษา',
    viewAll: 'ดูทั้งหมด',
  },
  testimonials: {
    badge: 'คำพูดของลูกค้า',
    title: 'ลูกค้าของเราพูดว่าอะไร',
    testimonial1: 'ข้อมูลเชิงกลยุทธ์ของ Prakit ปรับปรุง ROI สื่อของเราอย่างมาก ความเชี่ยวชาญและความเป็นมืออาชีพของพวกเขาไร้ใครเทียบ',
    testimonial1Name: 'สมชาย ท.',
    testimonial1Role: 'ผู้อำนวยการแบรนด์',
    testimonial2: 'การทำงานกับ Prakit เปลี่ยนวิธีการวางแผนสื่อของเรา วิธีการที่ใช้ข้อมูลของพวกเขาให้ผลลัพธ์ที่แท้จริง',
    testimonial2Name: 'สิริพร ป.',
    testimonial2Role: 'ผู้จัดการการตลาด',
    testimonial3: 'นาน 41 ปี Prakit ยังคงเป็นพันธมิตรที่เชื่อถือได้ของเรา ความรู้เกี่ยวกับตลาดของพวกเขามีค่าสำหรับแคมเปญของเรา',
    testimonial3Name: 'อานนท์ ล.',
    testimonial3Role: 'ซีอีโอ แบรนด์ชั้นนำ',
  },
  cta: {
    title: 'เพิ่มผลประกอบการสื่อของคุณด้วย Prakit',
    description: 'ทำงานกับสำนักงานสื่อชั้นนำของประเทศไทย ให้ผู้เชี่ยวชาญของเราสร้างกลยุทธ์สื่อที่ชนะ',
    button1: 'ติดต่อเรา',
    button2: 'เกี่ยวกับเรา',
  },
  mediaInsights: {
    badge: 'ข้อมูลเชิงลึกของสื่อ',
    title: 'แนวโน้มและเคล็ดลับสื่อล่าสุด',
    viewMore: 'อ่านเพิ่มเติม',
  },
  auth: {
    loginTitle: 'เข้าสู่ระบบ', loginSubtitle: 'ยินดีต้อนรับกลับมา! กรุณาเข้าสู่ระบบเพื่อดำเนินการต่อ',
    registerTitle: 'สมัครสมาชิก', registerSubtitle: 'สร้างบัญชีใหม่เพื่อเริ่มต้นเป็น Influencer',
    forgotPasswordTitle: 'ลืมรหัสผ่าน', forgotPasswordSubtitle: 'กรอกอีเมลของคุณเพื่อรับลิงก์รีเซ็ตรหัสผ่าน',
    resetPasswordTitle: 'รีเซ็ตรหัสผ่าน', resetPasswordSubtitle: 'กรอกรหัสผ่านใหม่ของคุณ',
    changePasswordTitle: 'เปลี่ยนรหัสผ่าน', changePasswordSubtitle: 'อัปเดตรหัสผ่านของคุณ',
    username: 'ชื่อผู้ใช้', password: 'รหัสผ่าน', email: 'อีเมล',
    confirmPassword: 'ยืนยันรหัสผ่าน', firstName: 'ชื่อ', lastName: 'นามสกุล',
    rememberMe: 'จดจำฉัน', forgotPassword: 'ลืมรหัสผ่าน?',
    noAccount: 'ยังไม่มีบัญชี?', haveAccount: 'มีบัญชีแล้ว?',
    registerNow: 'สมัครสมาชิก', loginNow: 'เข้าสู่ระบบ',
    sendResetLink: 'ส่งลิงก์รีเซ็ต', resetPassword: 'รีเซ็ตรหัสผ่าน',
    changePassword: 'เปลี่ยนรหัสผ่าน', oldPassword: 'รหัสผ่านเดิม', newPassword: 'รหัสผ่านใหม่',
    orContinueWith: 'หรือดำเนินการต่อด้วย', loginSuccess: 'เข้าสู่ระบบสำเร็จ',
    registerSuccess: 'สมัครสมาชิกสำเร็จ', passwordResetSent: 'ส่งลิงก์รีเซ็ตรหัสผ่านแล้ว',
    passwordChanged: 'เปลี่ยนรหัสผ่านสำเร็จ',
  },
  dashboard: {
    title: 'แดชบอร์ด', welcome: 'ยินดีต้อนรับกลับ', summary: 'สรุป',
    walletBalance: 'ยอดเงินในกระเป๋า', activeCampaigns: 'แคมเปญที่กำลังทำ',
    pendingTasks: 'งานที่ต้องส่ง', revisionTasks: 'งานที่ต้องแก้ไข',
    recentTransactions: 'ประวัติการรับเงินล่าสุด', notifications: 'การแจ้งเตือน',
    viewAll: 'ดูทั้งหมด', noNotifications: 'ไม่มีการแจ้งเตือน', markAsRead: 'อ่านแล้ว',
    newCampaign: 'แคมเปญใหม่', taskApproved: 'งานได้รับการอนุมัติ', paymentReceived: 'ได้รับการโอนเงิน',
  },
  profile: {
    title: 'โปรไฟล์', personalInfo: 'ข้อมูลส่วนตัว', socialAccounts: 'บัญชีโซเชียล',
    categories: 'หมวดหมู่ / Niche', rateCard: 'Rate Card',
    verification: 'ยืนยันตัวตน / KYC', verificationStatus: 'สถานะการยืนยัน',
    pending: 'รอตรวจสอบ', approved: 'อนุมัติแล้ว', rejected: 'ถูกปฏิเสธ',
    uploadDocument: 'อัปโหลดเอกสาร', idCard: 'บัตรประชาชน', selfie: 'เซลฟี่คู่บัตรประชาชน', bankBook: 'หน้าสมุดบัญชีธนาคาร',
    saveChanges: 'บันทึกการเปลี่ยนแปลง', editProfile: 'แก้ไขโปรไฟล์', bio: 'เกี่ยวกับฉัน',
    phone: 'เบอร์โทรศัพท์', location: 'ที่อยู่',
  },
  campaigns: {
    title: 'แคมเปญ', marketplace: 'ตลาดแคมเปญ', featured: 'แคมเปญแนะนำ',
    allCampaigns: 'แคมเปญทั้งหมด', filter: 'กรอง', category: 'หมวดหมู่', budget: 'งบประมาณ',
    followers: 'ผู้ติดตาม', platform: 'แพลตฟอร์ม', apply: 'สมัคร', applied: 'สมัครแล้ว',
    details: 'รายละเอียด', requirements: 'ข้อกำหนด', deadline: 'วันสิ้นสุด',
    influencersNeeded: 'ต้องการ Influencer', joined: 'เข้าร่วมแล้ว', budgetRange: 'ช่วงราคา',
  },
  tasks: {
    title: 'งาน', subtitle: 'จัดการงานแคมเปญของคุณ',
    myTasks: 'งานของฉัน', pending: 'รอดำเนินการ', inProgress: 'กำลังทำ',
    submitted: 'ส่งแล้ว', revision: 'ต้องแก้ไข', approved: 'อนุมัติแล้ว',
    waitingGoLive: 'รอ Go Live', done: 'Go Live ✓',
    noTasks: 'ไม่มีงานในหมวดหมู่นี้',
    campaign: 'แคมเปญ', dueDate: 'กำหนดส่ง', payment: 'ค่าตอบแทน',
    description: 'รายละเอียด',
    comments: 'ความคิดเห็น', noComments: 'ยังไม่มีความคิดเห็น',
    addComment: 'เพิ่มความคิดเห็น', commentPlaceholder: 'พิมพ์ความคิดเห็น...',
    postComment: 'โพสต์ความคิดเห็น',
    submitWork: 'ส่งงาน', resubmitWork: 'ส่งงานใหม่',
    draftContent: 'Draft Content / Caption',
    draftContentPlaceholder: 'เขียน caption หรือรายละเอียด content ที่จะโพสต์...',
    attachFile: 'แนบไฟล์ (รูป / วิดีโอ)', chooseFile: 'คลิกเพื่อเลือกไฟล์',
    revisionNote: 'ต้องแก้ไข', revisionDesc: 'กรุณาตรวจสอบ comment และ resubmit งาน',
    draftContentRevised: 'Draft Content / Caption (แก้ไขแล้ว)',
    draftContentRevisedPlaceholder: 'เขียน caption หรือรายละเอียด content ที่แก้ไขแล้ว...',
    attachFileRevised: 'แนบไฟล์ที่แก้ไขแล้ว (รูป / วิดีโอ)',
    readyGoLive: 'พร้อม Go Live แล้ว!',
    goLiveDesc: 'Draft ได้รับการอนุมัติ กรุณาโพสต์งานจริงและแนบลิ้งด้านล่าง',
    postUrl: 'ลิ้งโพสต์จริง (Post URL)', confirmGoLive: 'ยืนยัน Go Live',
    goneLive: 'Go Live เรียบร้อยแล้ว', postLink: 'ลิ้งโพสต์:',
    viewDetails: 'ดูรายละเอียด', attachments: 'ไฟล์แนบ', uploadFile: 'อัปโหลดไฟล์',
    due: 'กำหนดส่ง',
  },
  wallet: {
    title: 'กระเป๋าเงิน', balance: 'ยอดเงิน', transactionHistory: 'ประวัติธุรกรรม',
    income: 'รายรับ', withdrawal: 'ถอนเงิน', pending: 'รอดำเนินการ', completed: 'สำเร็จ',
    failed: 'ล้มเหลว', withdraw: 'ถอนเงิน', bankAccount: 'บัญชีธนาคาร', amount: 'จำนวนเงิน',
    requestWithdrawal: 'ขอถอนเงิน', noTransactions: 'ไม่มีธุรกรรม',
  },
  common: {
    loading: 'กำลังโหลด...', save: 'บันทึก', cancel: 'ยกเลิก', edit: 'แก้ไข', delete: 'ลบ',
    confirm: 'ยืนยัน', close: 'ปิด', search: 'ค้นหา', filter: 'กรอง', sort: 'เรียงลำดับ',
    next: 'ถัดไป', previous: 'ก่อนหน้า', submit: 'ส่ง', back: 'กลับ', more: 'เพิ่มเติม',
    readMore: 'อ่านเพิ่มเติม', viewAll: 'ดูทั้งหมด', seeDetails: 'ดูรายละเอียด',
    learnMore: 'เรียนรู้เพิ่มเติม', getStarted: 'เริ่มต้นใช้งาน', contactUs: 'ติดต่อเรา',
    followUs: 'ติดตามเรา', subscribe: 'สมัครรับข่าวสาร', emailPlaceholder: 'กรอกอีเมลของคุณ',
    allRightsReserved: 'สงวนลิขสิทธิ์', privacyPolicy: 'นโยบายความเป็นส่วนตัว',
    termsOfService: 'เงื่อนไขการใช้บริการ', cookiePolicy: 'นโยบายคุกกี้',
    companyName: 'บริษัท ประกิต โฮลดิ้งส์ จำกัด (มหาชน)',
    subject: 'หัวข้อ',
    message: 'ข้อความ',
  },
  footer: {
    description: 'สำนักงานสื่อชั้นนำของประเทศไทยที่มีประสบการณ์ 41 ปี ในการวางแผนและซื้อสื่อ',
    quickLinks: 'ลิงก์ด่วน', services: 'บริการ', newsletter: 'รับข่าวสาร',
    newsletterDesc: 'รับเคล็ดลับและอัปเดตสื่อล่าสุด', forInfluencers: 'สำหรับลูกค้า',
    forBrands: 'สำหรับเงิน', pricing: 'ราคา', support: 'ช่วยเหลือ',
  },
  contact: {
    badge: 'ติดต่อเรา',
    title: 'ติดต่อเรา',
    subtitle: 'มีคำถาม? เรายินดีรับฟัง ส่งข้อความหาเราและเราจะตอบกลับโดยเร็วที่สุด',
    info: {
      emailTitle: 'อีเมล',
      emailDesc: 'สำหรับข้อสงสัยทั่วไป',
      phoneTitle: 'โทรศัพท์',
      phoneDesc: 'จันทร์–ศุกร์ 9.00–18.00 น.',
      officeTitle: 'สำนักงาน',
      officeContent: 'กรุงเทพฯ, ประเทศไทย',
      officeDesc: '88 ซอยสุขุมวิท 62 แขวงพระโขนงใต้ เขตพระโขนง',
      hoursTitle: 'เวลาทำการ',
      hoursContent: 'จันทร์ – ศุกร์: 9.00 – 18.00 น.',
      hoursDesc: 'เสาร์–อาทิตย์: ปิดทำการ',
    },
    form: {
      title: 'ส่งข้อความถึงเรา',
      namePlaceholder: 'ชื่อของคุณ',
      emailPlaceholder: 'your@email.com',
      subjectPlaceholder: 'เราจะช่วยคุณได้อย่างไร?',
      messagePlaceholder: 'บอกรายละเอียดเพิ่มเติมเกี่ยวกับสิ่งที่ต้องการ...',
      sending: 'กำลังส่ง...',
      send: 'ส่งข้อความ',
      successTitle: 'ส่งข้อความแล้ว!',
      successDesc: 'เราจะติดต่อกลับหาคุณโดยเร็วที่สุด',
    },
    office: {
      title: 'เยี่ยมชมสำนักงานเรา',
      address: '88 ซอยสุขุมวิท 62 กรุงเทพฯ, ประเทศไทย',
    },
    faq: {
      title: 'คำถามที่พบบ่อย',
      description: 'ค้นหาคำตอบสำหรับคำถามทั่วไปได้ในส่วน FAQ ของเรา',
      button: 'ดู FAQ',
    },
  },
  error: {
    404: { title: 'ไม่พบหน้านี้', description: 'ขออภัย หน้าที่คุณกำลังค้นหาไม่มีอยู่', backHome: 'กลับหน้าหลัก' },
    500: { title: 'ข้อผิดพลาดของเซิร์ฟเวอร์', description: 'ขออภัย เกิดข้อผิดพลาดบางอย่าง กรุณาลองใหม่อีกครั้ง', tryAgain: 'ลองใหม่' },
  },
}

const enTranslations: Translations = {
  nav: {
    home: 'Home', about: 'About', services: 'Services', campaigns: 'Campaigns',
    blog: 'Blog', contact: 'Contact', joinInfluencer: 'Partnership',
    login: 'Login', register: 'Register', logout: 'Logout',
    dashboard: 'Dashboard', profile: 'Profile', wallet: 'Wallet',
    myCampaigns: 'My Campaigns', tasks: 'Tasks',
  },
  hero: {
    subtitle: 'Media Planning Excellence',
    title: 'Media Planning Excellence',
    description: '41 years of expertise in media strategy and planning. Thailand\'s trusted media agency partner delivering superior results.',
    getStarted: 'Get Consultation', exploreCampaigns: 'Our Services',
    stats: { influencers: 'Expert Strategists', brands: 'Since Established', paidOut: 'Of Excellence' },
  },
  about: {
    badge: 'About Us',
    title: 'Empowering Brands, Elevating Media Excellence',
    description: 'Thailand\'s premier media agency with 41 years of proven expertise in media planning, buying, and strategy',
    heroDescription: 'Prakit Media is Thailand\'s top media agency specializing in comprehensive media solutions. With 41 years of excellence, we partner with leading brands to create impactful media strategies.',
    points: {
      point1: '40+ Expert media planners and strategists',
      point2: 'Comprehensive media tools and Nielsen data access',
      point3: 'Superior media pricing through strong market networks',
    },
    learnMore: 'Learn More',
    stats: {
      stat1Value: '40+',
      stat1Label: 'Expert Strategists',
      stat2Value: '1978',
      stat2Label: 'Year Established',
      stat3Value: '41',
      stat3Label: 'Years of Excellence',
      stat4Value: '98%',
      stat4Label: 'Client Satisfaction',
    },
    story: {
      title: 'Our Story',
      paragraph1: 'Founded in 1978, Prakit Media started with a simple vision: to become Thailand\'s most trusted media planning partner. Over the past 41 years, we\'ve built deep relationships with media networks and developed proprietary insights that drive results.',
      paragraph2: 'Today, we leverage cutting-edge technology and data analytics to create media strategies that deliver measurable impact. Our team of 40+ expert media planners understands the nuances of every media channel and audience segment.',
      paragraph3: 'We\'re proud to partner with Thailand\'s leading brands, helping them maximize their media ROI and reach their target audiences with precision and creativity.',
    },
    values: {
      value1Title: 'Trust',
      value1Description: 'We build long-term partnerships based on transparency, integrity, and delivering on our promises.',
      value2Title: 'Excellence',
      value2Description: 'We pursue excellence in every aspect of our work, from strategy development to campaign execution.',
      value3Title: 'Innovation',
      value3Description: 'We embrace new technologies and methodologies to stay ahead of market trends.',
      value4Title: 'Partnership',
      value4Description: 'We see ourselves as true partners in our clients\' success, invested in their growth.',
    },
    team: {
      badge: 'Our Team',
      title: 'Meet the Experts Behind Prakit',
      member1Name: 'Somchai Prakit',
      member1Role: 'Founder & Chairman',
      member2Name: 'Siriporn Nakamura',
      member2Role: 'Managing Director',
      member3Name: 'Ananda Kittianan',
      member3Role: 'Head of Strategy',
      member4Name: 'Napak Suvanich',
      member4Role: 'Head of Digital',
    },
    whyUs: {
      badge: 'Why Choose Us',
      title: 'The Prakit Difference',
      feature1: '41 years of proven media expertise',
      feature2: 'Direct relationships with all major media networks',
      feature3: 'Advanced data analytics and Nielsen insights',
      feature4: 'Dedicated account management',
      feature5: 'Transparent, competitive pricing',
      feature6: 'Comprehensive reporting and optimization',
    },
  },
  services: {
    badge: 'Our Services',
    title: 'Everything You Need to Succeed',
    description: 'From annual planning to market intelligence, Prakit provides comprehensive media solutions tailored to your brand\'s needs.',
    service1: 'Annual Media Planning',
    service1Desc: 'Comprehensive yearly media strategy with in-depth analysis',
    service1Feature1: 'Comprehensive strategy',
    service1Feature2: 'Audience targeting',
    service1Feature3: 'Budget optimization',
    service1Feature4: 'Channel mix planning',
    service2: 'Media Buying',
    service2Desc: 'Secure media placements with best market rates',
    service2Feature1: 'Best market rates',
    service2Feature2: 'Secured placements',
    service2Feature3: 'Network relationships',
    service2Feature4: 'Flexible timing',
    service3: 'Monthly Analysis',
    service3Desc: 'Detailed spending and competitive market analysis',
    service3Feature1: 'Spending analysis',
    service3Feature2: 'Competitive insights',
    service3Feature3: 'Market trends',
    service3Feature4: 'Performance metrics',
    service4: 'Performance Reports',
    service4Desc: 'Echo media performance tracking and insights',
    service4Feature1: 'Real-time tracking',
    service4Feature2: 'Performance dashboards',
    service4Feature3: 'ROI analysis',
    service4Feature4: 'Optimization recommendations',
    service5: 'Strategic Consultation',
    service5Desc: '40+ experts providing professional guidance',
    service5Feature1: 'Expert guidance',
    service5Feature2: 'Strategic planning',
    service5Feature3: 'Market expertise',
    service5Feature4: 'Account management',
    service6: 'Market Intelligence',
    service6Desc: 'Access to Nielsen data and media trends',
    service6Feature1: 'Nielsen data access',
    service6Feature2: 'Market intelligence',
    service6Feature3: 'Trend forecasting',
    service6Feature4: 'Competitive analysis',
    howItWorks: {
      badge: 'How It Works',
      title: 'Simple, Transparent Process',
      step1Title: 'Strategy Development',
      step1Description: 'We analyze your brand goals and target audience to develop a customized media strategy.',
      step2Title: 'Media Planning',
      step2Description: 'Our experts plan the optimal channel mix and timeline to maximize your media ROI.',
      step3Title: 'Campaign Execution',
      step3Description: 'We secure placements and execute your campaign with precision and attention to detail.',
      step4Title: 'Performance Tracking',
      step4Description: 'Monitor real-time performance and receive regular insights to optimize your campaigns.',
    },
    ctaSection: {
      title: 'Ready to Transform Your Media Strategy?',
      description: 'Partner with Thailand\'s leading media agency and unlock your brand\'s full potential.',
      button1: 'Get Consultation',
      button2: 'Learn Our Story',
    },
  },
  expertise: {
    badge: 'Our Expertise',
    title: 'Media Solutions & Case Studies',
    viewAll: 'View All Cases',
  },
  testimonials: {
    badge: 'Client Testimonials',
    title: 'What Our Clients Say',
    testimonial1: 'Prakit\'s strategic insights significantly improved our media ROI. Their expertise and professionalism are unmatched.',
    testimonial1Name: 'Somchai T.',
    testimonial1Role: 'Brand Director',
    testimonial2: 'Working with Prakit transformed how we approach media planning. Their data-driven approach delivers real results.',
    testimonial2Name: 'Siriporn P.',
    testimonial2Role: 'Marketing Manager',
    testimonial3: 'In 41 years, Prakit continues to be our trusted partner. Their market knowledge is invaluable for our campaigns.',
    testimonial3Name: 'Ananda L.',
    testimonial3Role: 'CEO, Leading Brand',
  },
  cta: {
    title: 'Maximize Your Media ROI with Prakit',
    description: 'Partner with Thailand\'s leading media agency. Let our experts create your winning media strategy.',
    button1: 'Get in Touch',
    button2: 'Our Story',
  },
  mediaInsights: {
    badge: 'Media Insights',
    title: 'Latest Media Trends & Tips',
    viewMore: 'Read More',
  },
  auth: {
    loginTitle: 'Login', loginSubtitle: 'Welcome back! Please login to continue',
    registerTitle: 'Register', registerSubtitle: 'Create a new account to start as an Influencer',
    forgotPasswordTitle: 'Forgot Password', forgotPasswordSubtitle: 'Enter your email to receive a password reset link',
    resetPasswordTitle: 'Reset Password', resetPasswordSubtitle: 'Enter your new password',
    changePasswordTitle: 'Change Password', changePasswordSubtitle: 'Update your password',
    username: 'Username', password: 'Password', email: 'Email',
    confirmPassword: 'Confirm Password', firstName: 'First Name', lastName: 'Last Name',
    rememberMe: 'Remember me', forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?", haveAccount: 'Already have an account?',
    registerNow: 'Register now', loginNow: 'Login now',
    sendResetLink: 'Send Reset Link', resetPassword: 'Reset Password',
    changePassword: 'Change Password', oldPassword: 'Old Password', newPassword: 'New Password',
    orContinueWith: 'Or continue with', loginSuccess: 'Login successful',
    registerSuccess: 'Registration successful', passwordResetSent: 'Password reset link sent',
    passwordChanged: 'Password changed successfully',
  },
  dashboard: {
    title: 'Dashboard', welcome: 'Welcome back', summary: 'Summary',
    walletBalance: 'Wallet Balance', activeCampaigns: 'Active Campaigns',
    pendingTasks: 'Pending Tasks', revisionTasks: 'Tasks Need Revision',
    recentTransactions: 'Recent Transactions', notifications: 'Notifications',
    viewAll: 'View All', noNotifications: 'No notifications', markAsRead: 'Mark as read',
    newCampaign: 'New Campaign', taskApproved: 'Task Approved', paymentReceived: 'Payment Received',
  },
  profile: {
    title: 'Profile', personalInfo: 'Personal Information', socialAccounts: 'Social Accounts',
    categories: 'Categories / Niche', rateCard: 'Rate Card',
    verification: 'Verification / KYC', verificationStatus: 'Verification Status',
    pending: 'Pending', approved: 'Approved', rejected: 'Rejected',
    uploadDocument: 'Upload Document', idCard: 'ID Card', selfie: 'Selfie with ID', bankBook: 'Bank Book',
    saveChanges: 'Save Changes', editProfile: 'Edit Profile', bio: 'About Me',
    phone: 'Phone', location: 'Location',
  },
  campaigns: {
    title: 'Campaigns', marketplace: 'Campaign Marketplace', featured: 'Featured Campaigns',
    allCampaigns: 'All Campaigns', filter: 'Filter', category: 'Category', budget: 'Budget',
    followers: 'Followers', platform: 'Platform', apply: 'Apply', applied: 'Applied',
    details: 'Details', requirements: 'Requirements', deadline: 'Deadline',
    influencersNeeded: 'Influencers Needed', joined: 'Joined', budgetRange: 'Budget Range',
  },
  tasks: {
    title: 'Tasks', subtitle: 'Manage your campaign tasks',
    myTasks: 'My Tasks', pending: 'Pending', inProgress: 'In Progress',
    submitted: 'Submitted', revision: 'Needs Revision', approved: 'Approved',
    waitingGoLive: 'Awaiting Go Live', done: 'Go Live ✓',
    noTasks: 'No tasks in this category.',
    campaign: 'Campaign', dueDate: 'Due Date', payment: 'Payment',
    description: 'Description',
    comments: 'Comments', noComments: 'No comments yet.',
    addComment: 'Add Comment', commentPlaceholder: 'Type your comment...',
    postComment: 'Post Comment',
    submitWork: 'Submit Work', resubmitWork: 'Resubmit Work',
    draftContent: 'Draft Content / Caption',
    draftContentPlaceholder: 'Write your caption or content description...',
    attachFile: 'Attach File (Image / Video)', chooseFile: 'Click to choose file',
    revisionNote: 'Needs Revision', revisionDesc: 'Please review the comments and resubmit your work',
    draftContentRevised: 'Draft Content / Caption (Revised)',
    draftContentRevisedPlaceholder: 'Write your revised caption or content...',
    attachFileRevised: 'Attach Revised File (Image / Video)',
    readyGoLive: 'Ready to Go Live!',
    goLiveDesc: 'Draft approved. Please post your content and submit the link below.',
    postUrl: 'Post URL', confirmGoLive: 'Confirm Go Live',
    goneLive: 'Successfully Gone Live', postLink: 'Post Link:',
    viewDetails: 'View Details', attachments: 'Attachments', uploadFile: 'Upload File',
    due: 'Due',
  },
  wallet: {
    title: 'Wallet', balance: 'Balance', transactionHistory: 'Transaction History',
    income: 'Income', withdrawal: 'Withdrawal', pending: 'Pending', completed: 'Completed',
    failed: 'Failed', withdraw: 'Withdraw', bankAccount: 'Bank Account', amount: 'Amount',
    requestWithdrawal: 'Request Withdrawal', noTransactions: 'No transactions',
  },
  common: {
    loading: 'Loading...', save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete',
    confirm: 'Confirm', close: 'Close', search: 'Search', filter: 'Filter', sort: 'Sort',
    next: 'Next', previous: 'Previous', submit: 'Submit', back: 'Back', more: 'More',
    readMore: 'Read More', viewAll: 'View All', seeDetails: 'See Details',
    learnMore: 'Learn More', getStarted: 'Get Started', contactUs: 'Contact Us',
    followUs: 'Follow Us', subscribe: 'Subscribe', emailPlaceholder: 'Enter your email',
    allRightsReserved: 'All rights reserved', privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service', cookiePolicy: 'Cookie Policy',
    companyName: 'PRAKIT HOLDINGS PUBLIC COMPANY LIMITED',
    subject: 'Subject',
    message: 'Message',
  },
  footer: {
    description: "Thailand's leading media agency with 41 years of expertise in media planning and buying",
    quickLinks: 'Quick Links', services: 'Services', newsletter: 'Newsletter',
    newsletterDesc: 'Get the latest tips and media updates', forInfluencers: 'For Clients',
    forBrands: 'For Partners', pricing: 'Pricing', support: 'Support',
  },
  contact: {
    badge: 'Contact Us',
    title: 'Get in Touch',
    subtitle: "Have questions? We'd love to hear from you. Send us a message and we'll respond as soon as possible.",
    info: {
      emailTitle: 'Email',
      emailDesc: 'For general inquiries',
      phoneTitle: 'Phone',
      phoneDesc: 'Mon–Fri 9am–6pm',
      officeTitle: 'Office',
      officeContent: 'Bangkok, Thailand',
      officeDesc: '88 Soi Sukhumvit 62 Section 3, Phra Khanong Tai, Phra Khanong',
      hoursTitle: 'Working Hours',
      hoursContent: 'Mon – Fri: 9AM – 6PM',
      hoursDesc: 'Weekend: Closed',
    },
    form: {
      title: 'Send us a Message',
      namePlaceholder: 'Your name',
      emailPlaceholder: 'your@email.com',
      subjectPlaceholder: 'How can we help?',
      messagePlaceholder: 'Tell us more about your inquiry...',
      sending: 'Sending...',
      send: 'Send Message',
      successTitle: 'Message sent!',
      successDesc: "We'll get back to you as soon as possible.",
    },
    office: {
      title: 'Visit Our Office',
      address: '88 Soi Sukhumvit 62, Bangkok, Thailand',
    },
    faq: {
      title: 'Frequently Asked Questions',
      description: 'Find quick answers to common questions in our FAQ section.',
      button: 'View FAQ',
    },
  },
  error: {
    404: { title: 'Page Not Found', description: 'Sorry, the page you are looking for does not exist', backHome: 'Back to Home' },
    500: { title: 'Server Error', description: 'Sorry, something went wrong. Please try again later', tryAgain: 'Try Again' },
  },
}

export const useLanguageStore = defineStore('language', () => {
  const language = ref<Language>('th')

  function init() {
    if (import.meta.client) {
      const stored = localStorage.getItem('kol_language') as Language
      if (stored && (stored === 'th' || stored === 'en')) {
        language.value = stored
      }
    }
  }

  function setLanguage(lang: Language) {
    language.value = lang
    if (import.meta.client) {
      localStorage.setItem('kol_language', lang)
    }
  }

  function t(key: string): string {
    const translations = language.value === 'th' ? thTranslations : enTranslations
    const keys = key.split('.')
    let value: string | Translations = translations
    for (const k of keys) {
      if (typeof value === 'object' && value !== null && k in value) {
        value = value[k] as string | Translations
      } else {
        return key
      }
    }
    return typeof value === 'string' ? value : key
  }

  return { language, init, setLanguage, t }
})
